### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by brainwo** [brainwo/theme-detector#1]
- [ ] Direct support for `flutter/material.dart` theme data
- [ ] Direct support for [`fluent_ui`](https://github.com/bdlukaa/fluent_ui) theme data
- [ ] (Maybe) a support for `flutter/cupertino.dart`
- [ ] Linux specific
   - [ ] Get GTK theme colors
   - [ ] Get GTK icon resources
   - [ ] Get font resources
   - [ ] (Maybe) KDE/Qt theme support
